spring.application.name=engine
server.port=8080
definitionPath=D:\\projects\\ubml\\mte-prototype\\engine\\definition\\
eventPath=D:\\projects\\ubml\\mte-prototype\\engine\\eventsFile\\
liteflow.rule-source=flow\\**\\*.el.xml

database=lowcodeDemo
database.ip=10.176.34.96
spring.datasource.name=mysql_druid
spring.datasource.url=jdbc:mysql://${database.ip}:3306/${database}?characterEncoding=utf8&useSSL=false&allowMultiQueries=true&autoReconnect=true
spring.datasource.username=root
spring.datasource.password=3edc@WSX!QAZ

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource

mybatis-plus.mapper-locations=classpath*:mapper/*.xml
mybatis-plus.type-aliases-package=demo.lowcode.engine.model
